### ISSUE TITLE
Create a Search Page

### ISSUE THREAD

**Issue by michael-navazhylau-vu** [Veterans-United-Code-For-America/farmersmarkets-for-all#11]
> As a user, I would like to be able to input my state or zip code to find farmers markets close to me.

AC:

When a user visits the search page, they are presented with a search form with two options: State and Zip Code.
User can input either a state or a zip code.

Database Tables:
N/A

API Endpoints:
N/A

Additional Notes:
The search form should be designed to prevent invalid or incorrect inputs, such as invalid zip codes or non-existent states.

**Comment by Jazzyb21** [comment]
Possible color palettes: https://github.com/Veterans-United-Code-For-America/farmersmarkets-for-all/discussions/19
